### ISSUE TITLE
Include @nx/devkit as a dependency

### ISSUE THREAD

**Issue by isaacplmann** [marksandspencer/nx-plugins#106]
This plugin doesn't have an Nx version listed in the [Nx Plugin Registry](https://nx.dev/extending-nx/registry) because the plugin doesn't include `@nx/devkit` as a dependency.  Could you please release a version that fixes that?

Thanks,
Isaac (Nx Team)

**Comment by azerafati** [comment]
This is also causing me a problem. Trying to run with nx 15.9.4 and playwirght 1.37.1.
 I‌ get the error 
 `Cannot find module '@nx/devkit'`

**Comment by WanielDeiss** [comment]
i have the same problem after upgrading nx to 20.x
